
workflows:
  build_android:
    name: Build Android APK
    max_build_duration: 60
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor
      - name: Fetch Dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
